name: Lint and Unit Tests

on:
  workflow_dispatch:
    inputs:
      working-directory:
        description: Working directory
        required: true
        default: .
      nodejs-version:
        description: Node.js version
        required: true
        default: lts/*

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/nodejs/lint
        with:
          nodejs-version: 22.x

      - name: Run Unit Tests
        run: npm run test:unit-coverage
