name: Node.js - Build, Lint, Unit Tests

on:
  workflow_call:
    inputs:
      nodejs-version:
        description: Node.js version
        required: true
        default: 'lts/*'
        type: string
      working-directory:
        description: Working directory
        required: false
        default: '.'
        type: string
      storybook-playwright-install-flag:
        description: Install playwright for Storybook tests
        required: false
        default: 'false'
        type: string

jobs:
  print-inputs:
    runs-on: ubuntu-latest

    steps:
      - name: Print inputs
        shell: sh
        run: |
          echo "Input - nodejs-version: ${{ inputs.nodejs-version }}"
          echo "Input - working-directory: ${{ inputs.working-directory }}"
          echo "Input - storybook-playwright-install-flag: ${{ inputs.storybook-playwright-install-flag }}"

  test-unit-coverage:
    name: Run Unit Tests with Coverage
    runs-on: ubuntu-latest

    steps:
      - name: actions checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: darrylmorton/ct-continuous-workflows/.github/actions/nodejs-setup@v1
        with:
          nodejs-version: ${{ inputs.nodejs-version }}

      - name: Install Node.js Dependencies
        uses: darrylmorton/ct-continuous-workflows/.github/actions/nodejs-install-dependencies@v1

      - name: Lint
        uses: darrylmorton/ct-continuous-workflows/.github/actions/nodejs-lint@v1

      - if: inputs.storybook-playwright-install-flag == 'true'
        name: Install Playwright
        uses: darrylmorton/ct-continuous-workflows/.github/actions/nodejs-install-playwright@v1

      - name: Run Unit Tests
        working-directory: ${{ inputs.working-directory }}
        shell: sh
        run: npm run test:unit-coverage
